import java.util.ArrayList;
import java.util.List;

public class Countries {

    public static List<String> countries = new ArrayList();
    public static List<String> countriesId = new ArrayList();


    public static void init() {

        countriesId.add("AF");
        countriesId.add("AL");
        countriesId.add("DZ");
        countriesId.add("AD");
        countriesId.add("AO");
        countriesId.add("AI");
        countriesId.add("AQ");
        countriesId.add("AG");
        countriesId.add("SA");
        countriesId.add("AR");
        countriesId.add("AM");
        countriesId.add("AW");
        countriesId.add("AU");
        countriesId.add("AT");
        countriesId.add("AZ");
        countriesId.add("BS");
        countriesId.add("BH");
        countriesId.add("BD");
        countriesId.add("BB");
        countriesId.add("BE");
        countriesId.add("BZ");
        countriesId.add("BJ");
        countriesId.add("BM");
        countriesId.add("BT");
        countriesId.add("BY");
        countriesId.add("BO");
        countriesId.add("BQ");
        countriesId.add("BA");
        countriesId.add("BW");
        countriesId.add("BR");
        countriesId.add("BN");
        countriesId.add("IO");
        countriesId.add("BG");
        countriesId.add("BF");
        countriesId.add("BI");
//        countriesId.add("XC");
        countriesId.add("CL");
        countriesId.add("CN");
        countriesId.add("CW");
        countriesId.add("HR");
        countriesId.add("CY");
        countriesId.add("TD");
        countriesId.add("ME");
        countriesId.add("CZ");
        countriesId.add("DK");
        countriesId.add("DM");
        countriesId.add("DO");
        countriesId.add("DJ");
        countriesId.add("EG");
        countriesId.add("EC");
        countriesId.add("ER");
        countriesId.add("EE");
        countriesId.add("ET");
        countriesId.add("FK");
        countriesId.add("FJ");
        countriesId.add("PH");
        countriesId.add("FI");
        countriesId.add("TF");
        countriesId.add("FR");
        countriesId.add("GA");
        countriesId.add("GM");
        countriesId.add("GH");
        countriesId.add("GI");
        countriesId.add("GR");
        countriesId.add("GD");
        countriesId.add("GL");
        countriesId.add("GE");
        countriesId.add("GU");
        countriesId.add("GY");
        countriesId.add("GT");
        countriesId.add("GN");
        countriesId.add("GQ");
        countriesId.add("GW");
        countriesId.add("HT");
        countriesId.add("ES");
        countriesId.add("HN");
        countriesId.add("HK");
        countriesId.add("IN");
        countriesId.add("ID");
        countriesId.add("IQ");
        countriesId.add("IR");
        countriesId.add("IE");
        countriesId.add("IS");
        countriesId.add("IL");
        countriesId.add("JM");
        countriesId.add("JP");
        countriesId.add("YE");
        countriesId.add("JO");
        countriesId.add("KY");
        countriesId.add("KH");
        countriesId.add("CM");
        countriesId.add("CA");
        countriesId.add("QA");
        countriesId.add("KZ");
        countriesId.add("KE");
        countriesId.add("KG");
        countriesId.add("KI");
        countriesId.add("CO");
        countriesId.add("KM");
        countriesId.add("CG");
        countriesId.add("CD");
        countriesId.add("KP");
        countriesId.add("XK");
        countriesId.add("CR");
//        countriesId.add("QV");
        countriesId.add("CU");
        countriesId.add("KW");
        countriesId.add("LA");
        countriesId.add("LS");
        countriesId.add("LB");
        countriesId.add("LR");
        countriesId.add("LY");
        countriesId.add("LI");
        countriesId.add("LT");
        countriesId.add("LU");
        countriesId.add("LV");
        countriesId.add("MK");
        countriesId.add("MG");
        countriesId.add("YT");
        countriesId.add("MO");
        countriesId.add("MW");
        countriesId.add("MV");
        countriesId.add("MY");
        countriesId.add("ML");
        countriesId.add("MT");
        countriesId.add("MP");
        countriesId.add("MA");
        countriesId.add("MR");
        countriesId.add("MU");
        countriesId.add("MX");
//        countriesId.add("XL");
        countriesId.add("FM");
//        countriesId.add("UM");
        countriesId.add("MD");
        countriesId.add("MN");
        countriesId.add("MS");
        countriesId.add("MZ");
//        countriesId.add("MM");
        countriesId.add("NA");
        countriesId.add("NR");
        countriesId.add("NP");
        countriesId.add("NL");
        countriesId.add("DE");
        countriesId.add("NE");
        countriesId.add("NG");
        countriesId.add("NI");
        countriesId.add("NU");
        countriesId.add("NF");
        countriesId.add("NO");
        countriesId.add("NC");
        countriesId.add("NZ");
        countriesId.add("PS");
        countriesId.add("OM");
        countriesId.add("PK");
        countriesId.add("PW");
        countriesId.add("PA");
        countriesId.add("PG");
        countriesId.add("PY");
        countriesId.add("PE");
        countriesId.add("PN");
        countriesId.add("PF");
        countriesId.add("PL");
        countriesId.add("ZA");
        countriesId.add("GS");
        countriesId.add("PT");
//        countriesId.add("KR");
        countriesId.add("CF");
        countriesId.add("RU");
        countriesId.add("RW");
        countriesId.add("EH");
        countriesId.add("BL");
        countriesId.add("RO");
        countriesId.add("SV");
        countriesId.add("WS");
        countriesId.add("AS");
        countriesId.add("SM");
        countriesId.add("SN");
        countriesId.add("XS");
        countriesId.add("SC");
        countriesId.add("SL");
        countriesId.add("SG");
        countriesId.add("SZ");
        countriesId.add("SK");
        countriesId.add("SI");
        countriesId.add("SO");
        countriesId.add("LK");
        countriesId.add("PM");
        countriesId.add("KN");
        countriesId.add("LC");
        countriesId.add("VC");
        countriesId.add("US");
        countriesId.add("SD");
//        countriesId.add("SS");
        countriesId.add("SR");
        countriesId.add("SY");
        countriesId.add("CH");
        countriesId.add("SE");
        countriesId.add("SH");
        countriesId.add("TJ");
        countriesId.add("TH");
        countriesId.add("TW");
        countriesId.add("TZ");
        countriesId.add("TG");
        countriesId.add("TK");
        countriesId.add("TO");
        countriesId.add("TT");
        countriesId.add("TN");
        countriesId.add("TR");
        countriesId.add("TM");
        countriesId.add("TC");
        countriesId.add("TV");
        countriesId.add("UG");
        countriesId.add("UA");
        countriesId.add("UY");
        countriesId.add("UZ");
        countriesId.add("VU");
        countriesId.add("WF");
        countriesId.add("VA");
        countriesId.add("VE");
        countriesId.add("HU");
        countriesId.add("GB");
        countriesId.add("VN");
        countriesId.add("IT");
        countriesId.add("TL");
        countriesId.add("CI");
        countriesId.add("BV");
        countriesId.add("CX");
        countriesId.add("CK");
        countriesId.add("VI");
        countriesId.add("VG");
        countriesId.add("HM");
        countriesId.add("CC");
        countriesId.add("FO");
        countriesId.add("MH");
        countriesId.add("SB");
        countriesId.add("SX");
        countriesId.add("ST");
        countriesId.add("ZM");
//        countriesId.add("QR");
        countriesId.add("CV");
        countriesId.add("ZW");
        countriesId.add("AE");
        countriesId.add("XI");


        countries.add("Afganistan");
        countries.add("Albania");
        countries.add("Algieria");
        countries.add("Andora");
        countries.add("Angola");
        countries.add("Anguilla");
        countries.add("Antarktyda");
        countries.add("Antigua i Barbuda");
        countries.add("Arabia Saudyjska");
        countries.add("Argentyna");
        countries.add("Armenia");
        countries.add("Aruba");
        countries.add("Australia");
        countries.add("Austria");
        countries.add("Azerbejdżan");
        countries.add("Bahamy");
        countries.add("Bahrajn");
        countries.add("Bangladesz");
        countries.add("Barbados");
        countries.add("Belgia");
        countries.add("Belize");
        countries.add("Benin");
        countries.add("Bermudy");
        countries.add("Bhutan");
        countries.add("Białoruś");
        countries.add("Boliwia");
        countries.add("Bonaire");
        countries.add("Bośnia i Hercegowina");
        countries.add("Botswana");
        countries.add("Brazylia");
        countries.add("Brunei");
        countries.add("Brytyjskie Terytorium Oceanu Indyjskiego");
        countries.add("Bułgaria");
        countries.add("Burkina Faso");
        countries.add("Burundi");
//        countries.add("Ceuta");
        countries.add("Chile");
        countries.add("Chiny");
        countries.add("Curaçao");
        countries.add("Chorwacja");
        countries.add("Cypr");
        countries.add("Czad");
        countries.add("Czarnogóra");
        countries.add("Czechy");
        countries.add("Dania");
        countries.add("Dominika");
        countries.add("Dominikana");
        countries.add("Dżibuti");
        countries.add("Egipt");
        countries.add("Ekwador");
        countries.add("Erytrea");
        countries.add("Estonia");
        countries.add("Etiopia");
        countries.add("Falklandy");
        countries.add("Fidżi");
        countries.add("Filipiny");
        countries.add("Finlandia");
        countries.add("Francuskie Terytoria Południowe");
        countries.add("Francja");
        countries.add("Gabon");
        countries.add("Gambia");
        countries.add("Ghana");
        countries.add("Gibraltar");
        countries.add("Grecja");
        countries.add("Grenada");
        countries.add("Grenlandia");
        countries.add("Gruzja");
        countries.add("Guam");
        countries.add("Gujana");
        countries.add("Gwatemala");
        countries.add("Gwinea");
        countries.add("Gwinea Równikowa");
        countries.add("Gwinea-Bissau");
        countries.add("Haiti");
        countries.add("Hiszpania");
        countries.add("Honduras");
        countries.add("Hongkong");
        countries.add("Indie");
        countries.add("Indonezja");
        countries.add("Irak");
        countries.add("Iran");
        countries.add("Irlandia");
        countries.add("Islandia");
        countries.add("Izrael");
        countries.add("Jamajka");
        countries.add("Japonia");
        countries.add("Jemen");
        countries.add("Jordania");
        countries.add("Kajmany");
        countries.add("Kambodża");
        countries.add("Kamerun");
        countries.add("Kanada");
        countries.add("Katar");
        countries.add("Kazachstan");
        countries.add("Kenia");
        countries.add("Kirgistan");
        countries.add("Kiribati");
        countries.add("Kolumbia");
        countries.add("Komory");
        countries.add("Kongo");
        countries.add("Kongo, Republika Demokratyczna");
        countries.add("Korea Południowa");
        countries.add("Kosowo");
        countries.add("Kostaryka");
//        countries.add("Kraje i terytoria niewyszczególnione w ramach handlu wewnątrzunijnego");
        countries.add("Kuba");
        countries.add("Kuwejt");
        countries.add("Laos");
        countries.add("Lesoto");
        countries.add("Liban");
        countries.add("Liberia");
        countries.add("Libia");
        countries.add("Liechtenstein");
        countries.add("Litwa");
        countries.add("Luksemburg");
        countries.add("Łotwa");
        countries.add("Macedonia");
        countries.add("Madagaskar");
        countries.add("Majotta");
        countries.add("Makau");
        countries.add("Malawi");
        countries.add("Malediwy");
        countries.add("Malezja");
        countries.add("Mali");
        countries.add("Malta");
        countries.add("Mariany Północne");
        countries.add("Maroko");
        countries.add("Mauretania");
        countries.add("Mauritius");
        countries.add("Meksyk");
//        countries.add("Melilla");
        countries.add("Mikronezja");
//        countries.add("Minor (Powiernicze Wyspy Pacyfiku Stanów Zjednoczonych)");
        countries.add("Mołdawia");
        countries.add("Mongolia");
        countries.add("Montserrat");
        countries.add("Mozambik");
//        countries.add("Myanmar (Burma)");
        countries.add("Namibia");
        countries.add("Nauru");
        countries.add("Nepal");
        countries.add("Holandia");
        countries.add("Niemcy");
        countries.add("Niger");
        countries.add("Nigeria");
        countries.add("Nikaragua");
        countries.add("Niue");
        countries.add("Norfolk");
        countries.add("Norwegia");
        countries.add("Nowa Kaledonia");
        countries.add("Nowa Zelandia");
        countries.add("Terytoria Palestyńskie");
        countries.add("Oman");
        countries.add("Pakistan");
        countries.add("Palau");
        countries.add("Panama");
        countries.add("Papua-Nowa Gwinea");
        countries.add("Paragwaj");
        countries.add("Peru");
        countries.add("Pitcairn");
        countries.add("Polinezja Francuska");
        countries.add("Polska");
        countries.add("Republika Południowej Afryki");
        countries.add("Georgia Południowa i Sandwich Południowy");
        countries.add("Portugalia");
//        countries.add("Republika Korei");
        countries.add("Republika Środkowoafrykańska");
        countries.add("Rosja");
        countries.add("Rwanda");
        countries.add("Sahara Zachodnia");
        countries.add("St. Barthelemy");
        countries.add("Rumunia");
        countries.add("Salwador");
        countries.add("Samoa");
        countries.add("Samoa Amerykańskie");
        countries.add("San Marino");
        countries.add("Senegal");
        countries.add("Serbia");
        countries.add("Seszele");
        countries.add("Sierra Leone");
        countries.add("Singapur");
        countries.add("Suazi");
        countries.add("Słowacja");
        countries.add("Słowenia");
        countries.add("Somalia");
        countries.add("Sri Lanka");
        countries.add("Saint Pierre i Miquelon");
        countries.add("St. Kitts i Nevis");
        countries.add("St. Lucia");
        countries.add("St. Vincent i Grenadyny");
        countries.add("Stany Zjednoczone");
        countries.add("Sudan");
//        countries.add("Sudan Południowy");
        countries.add("Surinam");
        countries.add("Syria");
        countries.add("Szwajcaria");
        countries.add("Szwecja");
        countries.add("Wyspa Świętej Heleny");
        countries.add("Tadżykistan");
        countries.add("Tajlandia");
        countries.add("Tajwan");
        countries.add("Tanzania");
        countries.add("Togo");
        countries.add("Tokelau");
        countries.add("Tonga");
        countries.add("Trynidad i Tobago");
        countries.add("Tunezja");
        countries.add("Turcja");
        countries.add("Turkmenistan");
        countries.add("Turks i Caicos Wyspy");
        countries.add("Tuvalu");
        countries.add("Uganda");
        countries.add("Ukraina");
        countries.add("Urugwaj");
        countries.add("Uzbekistan");
        countries.add("Vanuatu");
        countries.add("Wyspy Wallis i Futuna");
        countries.add("Watykan");
        countries.add("Wenezuela");
        countries.add("Węgry");
        countries.add("Wielka Brytania");
        countries.add("Wietnam");
        countries.add("Włochy");
        countries.add("Timor Wschodni");
        countries.add("Wybrzeże Kości Słoniowej");
        countries.add("Wyspa Bouveta");
        countries.add("Wyspa Bożego Narodzenia");
        countries.add("Wyspy Cooka");
        countries.add("Wyspy Dziewicze (USA)");
        countries.add("Bryt. Wyspy Dziewicze");
        countries.add("Wyspy Heard i McDonald");
        countries.add("Wyspy Kokosowe");
        countries.add("Wyspy Owcze");
        countries.add("Wyspy Marshalla");
        countries.add("Wyspy Salomona");
        countries.add("St. Maarten i St. Martin");
        countries.add("Wyspy Świętego Tomasza i Książęca");
        countries.add("Zambia");
//        countries.add("Zapasy i zaopatrzenie statków w ramach handlu wewnątrzunijnego");
        countries.add("Wyspy Zielonego Przylądka");
        countries.add("Zimbabwe");
        countries.add("Zjednoczone Emiraty Arabskie");
        countries.add("Irlandia Północna");


    }

}
